In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("amaymishra11/tech-layoffs-and-hiring-trends-2026")

print("Path to dataset files:", path)

c:\Users\Victus\Desktop\Machine Learning\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Victus\.cache\kagglehub\datasets\amaymishra11\tech-layoffs-and-hiring-trends-2026\1.archive...

100%|██████████| 450k/450k [00:01<00:00, 454kB/s]

Extracting files...
Path to dataset files: C:\Users\Victus\.cache\kagglehub\datasets\amaymishra11\tech-layoffs-and-hiring-trends-2026\versions\1

In [6]:
df=pd.read_csv(f'{path}/tech_layoffs_hiring_trends_elite_v2.csv')

df.head()

,record_id,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,...,hiring_trend,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition
0,T0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860,1.8,AI Automation,...,Moderate Hiring,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market
1,T1,Palantir,AI,Canada,Big Tech,Feb,2024,955,1.8,Cost Cutting,...,Moderate Hiring,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market
2,T2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,18912,9.5,Overhiring Correction,...,Hiring Freeze,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession
3,T3,Spotify,Gaming,USA,Mid-size,Jun,2025,18159,9.1,Cost Cutting,...,Hiring Freeze,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession
4,T4,Uber,Gaming,UK,Startup,Feb,2025,815,3.3,Market Slowdown,...,Moderate Hiring,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market

In [7]:
df.shape

(12000, 23)

In [8]:
df.isnull().sum()

record_id                 0
company_name              0
industry                  0
country                   0
company_size              0
month                     0
year                      0
layoffs_count             0
layoff_percentage         0
reason_for_layoffs        0
ai_automation_impact      0
ai_replacement_risk       0
open_roles                0
hiring_trend              0
remote_jobs_percentage    0
top_hiring_role           0
stock_growth_percent      0
revenue_growth_percent    0
salary_budget_change      0
ai_adoption_level         0
employee_sentiment        0
job_security_score        0
market_condition          0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.dtypes

record_id                     str
company_name                  str
industry                      str
country                       str
company_size                  str
month                         str
year                        int64
layoffs_count               int64
layoff_percentage         float64
reason_for_layoffs            str
ai_automation_impact      float64
ai_replacement_risk       float64
open_roles                  int64
hiring_trend                  str
remote_jobs_percentage    float64
top_hiring_role               str
stock_growth_percent      float64
revenue_growth_percent    float64
salary_budget_change      float64
ai_adoption_level         float64
employee_sentiment        float64
job_security_score        float64
market_condition              str
dtype: object

In [ ]:
df=df.drop(columns=['record_id'])

In [14]:
df.dtypes

company_name                  str
industry                      str
country                       str
company_size                  str
month                         str
year                        int64
layoffs_count               int64
layoff_percentage         float64
reason_for_layoffs            str
ai_automation_impact      float64
ai_replacement_risk       float64
open_roles                  int64
hiring_trend                  str
remote_jobs_percentage    float64
top_hiring_role               str
stock_growth_percent      float64
revenue_growth_percent    float64
salary_budget_change      float64
ai_adoption_level         float64
employee_sentiment        float64
job_security_score        float64
market_condition              str
dtype: object

In [15]:
obj=LabelEncoder()

df['company_name']=obj.fit_transform(df['company_name'])
df['industry']=obj.fit_transform(df['industry'])
df['country']=obj.fit_transform(df['country'])
df['company_size']=obj.fit_transform(df['company_size'])
df['month']=obj.fit_transform(df['month'])
df['reason_for_layoffs']=obj.fit_transform(df['reason_for_layoffs'])
df['hiring_trend']=obj.fit_transform(df['hiring_trend'])
df['top_hiring_role']=obj.fit_transform(df['top_hiring_role'])

In [16]:
df.dtypes

company_name                int64
industry                    int64
country                     int64
company_size                int64
month                       int64
year                        int64
layoffs_count               int64
layoff_percentage         float64
reason_for_layoffs          int64
ai_automation_impact      float64
ai_replacement_risk       float64
open_roles                  int64
hiring_trend                int64
remote_jobs_percentage    float64
top_hiring_role             int64
stock_growth_percent      float64
revenue_growth_percent    float64
salary_budget_change      float64
ai_adoption_level         float64
employee_sentiment        float64
job_security_score        float64
market_condition              str
dtype: object

In [20]:
df.head()

,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,ai_automation_impact,...,hiring_trend,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition
0,9,0,3,1,7,2026,860,1.8,0,6.4,...,3,46.7,5,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market
1,14,0,0,0,3,2024,955,1.8,1,0.9,...,3,58.9,5,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market
2,3,2,5,2,0,2025,18912,9.5,3,7.1,...,2,85.4,4,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession
3,17,5,5,2,6,2025,18159,9.1,1,10.4,...,2,44.0,4,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession
4,19,5,4,3,3,2025,815,3.3,2,11.4,...,3,53.2,4,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market

In [21]:
print(df.to_string())

       company_name  industry  country  company_size  month  year  layoffs_count  layoff_percentage  reason_for_layoffs  ai_automation_impact  ai_replacement_risk  open_roles  hiring_trend  remote_jobs_percentage  top_hiring_role  stock_growth_percent  revenue_growth_percent  salary_budget_change  ai_adoption_level  employee_sentiment  job_security_score market_condition
0                 9         0        3             1      7  2026            860                1.8                   0                   6.4                  5.0        5426             3                    46.7                5                 -25.7                    30.3                   4.9                4.4                 8.7                 8.6      Bull Market
1                14         0        0             0      3  2024            955                1.8                   1                   0.9                  1.1        9666             3                    58.9                5                  -5.6                     6.1                   1.5                1.0                 8.2                 7.2      Bull Market
2                 3         2        5             2      0  2025          18912                9.5                   3                   7.1                  3.9         437             2                    85.4                4                   7.0                   -23.6                 -14.9                5.6                 4.5                 5.9        Recession
3                17         5        5             2      6  2025          18159                9.1                   1                  10.4                  7.4        1075             2                    44.0                4                  31.6                   -22.3                  -1.6                6.5                 5.4                 4.7        Recession
4                19         5        4             3      3  2025            815                3.3                   2                  11.4                 10.0         537             3                    53.2                4                  85.3                    26.6                   9.8                9.3                 6.7                 5.8      Bull Market
5                 5         4        5             0      5  2024           3568               32.7                   3                   0.9                  8.4         642             1                    66.9                2                  36.8                    53.7                  15.2                1.1                 7.7                 5.4        Recession
6                 0         5        3             1      2  2024           3454               29.4                   0                   6.7                 10.0        1620             1                    47.8                6                  51.3                    39.7                  10.8                5.0                 6.9                 4.2        Recession
7                 1         5        4             3      5  2025           1038                1.1                   4                   6.2                  5.8         763             3                    55.1                2                 -26.2                    26.4                  13.9                5.7                 6.5                 8.4      Bull Market
8                 7         1        4             1      2  2026           1819                9.3                   0                   9.5                 10.0        5347             3                    27.5                0                  74.2                     2.6                  -6.1                6.4                 5.8                 6.0      Bull Market
9                 5         6        2             2      5  2025           1306                4.3                   3                   5.1                  3.5        5775             3                    52.7                3                  48.5                    -2.1                  -5.5                3.4                 5.3                 6.2      Bull Market
10                1         6        4             3      6  2025           1136                0.6                   2                   5.3                  5.4        1836             2                    32.8                7                  37.3                    17.7                   0.9                6.0                 6.6                 8.2      Bull Market
11                2         1        0             1      5  2026           1153                5.3                   4                   3.5                  4.8        3710             2                    70.9                3                  53.3                     6.3                   5.2                3.2                 7.3                 6.8      Bull Market
12                4         4        2             2      2  2026          10339               24.3                   4                   2.5                  6.6         452             1                    66.9                0                   2.1                   -16.8                  -4.3                1.8                 4.1                 3.8        Recession
13               18         3        4             2      3  2024           1802                3.4                   0                   6.2                 10.0        5930             3                    28.3                3                  87.6                    18.9                   6.0                8.5                 9.3                 7.2      Bull Market
14                4         6        2             0      5  2025           8158               18.8                   3                   5.9                 10.0         201             2                    42.4                2                  69.9                    54.5                  24.9                6.0                 7.8                 5.9        Recession
15               15         2        4             3      9  2026           6592               29.2                   2                   2.7                  8.9         871             2                    45.9                2                 -21.3                   -23.5                 -16.1                4.4                 2.7                 2.3        Recession
16               16         0        4             0      4  2026           1218                6.6                   2                   9.4                  5.4        4446             3                    30.0                2                  87.2                    16.4                  16.6                7.7                 6.7                 6.5      Bull Market
17                3         5        2             3      9  2026           8022               23.8                   3                   5.5                 10.0         596             1                    71.5                0                  89.3                    14.9                  -2.2                6.8                 7.1                 4.6        Recession
18               19         1        4             2     10  2025           4420               21.7                   4                  16.0                 10.0         240             2                    34.5                7                  -8.8                    16.2                   2.2                9.6                 5.3                 5.0        Recession
19                6         0        4             1      0  2026            625                6.2                   0                  15.9                  7.3        2409             3                    35.8                5                 -26.6                    35.3                  18.0                9.4                 6.7                 6.8      Bull Market
20                2         6        1             3      7  2026          11647               37.2                   4                   3.8                 10.0         370             1                    15.7                5                 -38.1                    50.4                   1.2                3.3                 5.9                 3.7        Recession
21               14         1        4             0      2  2025             50                4.7                   4                   8.4                  6.8        1915             2                    13.1                6                  27.5                     2.8                   9.8                7.0                 5.8                 7.2      Bull Market
22                7         3        0             0      0  2024            773                0.5                   2                   6.0                  6.0        4564             3                    87.6                6                 -39.5                     8.9                   4.6                5.1                 8.2                 6.5      Bull Market
23                6         2        0             2      4  2024           6949               34.8                   0                   3.7                  8.1         562             1                    45.4                6                 -32.3                    -9.5                  -4.2                2.7                 4.5                 2.6        Recession
24                1         0        5             1      8  2026            580                6.1                   4                   7.3                  5.8        8253             3                    11.2                5                 -38.8                   -21.5                   0.1                6.9                 6.7                 5.5      Bull Market
25               19         2        2             0      5  2024           2479                8.1                   0                   1.9                  4.1        3049             2                    30.9                3                  81.0                    17.6                   6.3                1.9                 7.6                 7.1      Bull Market
26                9         6        1             1      1  2026           6501                1.5                   0                  11.8                 10.0        3946             3                    61.5                4                  28.7                    55.0                  24.0                9.5                10.0                 8.3           Stable
27                9         0        1             1      0  2024           2444                2.1                   3                   2.8                  2.4        9967             0                    40.8                5                   1.0                    -2.8                  -0.4                2.8                 7.5                 6.9      Bull Market
28               15         1        1             2      0  2024            828               14.7                   4                   8.6                 10.0        2986             3                    89.2                3                   5.2                    41.0                  13.5                9.4                 8.8                 6.5           Stable
29               14         0        5             3      7  2025           1548                7.4                   4                   4.2                  5.9        9787             3                    76.1                5                  75.9                     8.1                  -6.3                4.9                 8.3                 5.5      Bull Market
30               12         1        1             3      4  2025            717                6.8                   2                   4.4                  3.6        3340             2                    33.5                4                  45.8                    39.0                  21.3                3.9                 8.8                 7.0      Bull Market
31               15         4        1             0      8  2024           2445                5.5                   0                   5.9                  8.0        5046             3                    21.4                6                  38.5                   -16.4                 -13.8                5.4                 6.9                 4.5      Bull Market
32               18         6        0             3      4  2024          18924               24.4                   3                   7.2                 10.0        1415             2                    75.0                1                  88.1                    39.0                  10.0                8.4                 4.6                 5.3        Recession
33               12         2        0             2      7  2024             90                2.5                   3                   5.8                  5.1        5049             3                    47.5                2                 -29.0                   -15.0                  -0.8                6.0                 7.3                 6.4      Bull Market
34                2         6        2             0     10  2026           1214                4.8                   0                   6.7                 10.0        2305             3                    11.0                6                 -39.2                    50.7                  24.2                9.7                10.0                 6.2      Bull Market
35                5         0        1             1      9  2026           5751                2.3                   2                   4.7                  3.9        4584             3                    60.2                5                  76.7                   -21.1                 -10.5                6.0                 8.0                 7.1           Stable
36                1         4        1             2      1  2025           1667               18.7                   0                   4.0                  9.1        1389             1                    56.7                0                  86.5                    58.8                  24.4                5.1                 7.4                 5.7        Recession
37                6         3        0             3     11  2025            924                1.3                   1                   5.7                 10.0        5004             3                    59.1                6                  80.9                    48.6                  14.1                8.3                 6.5                 7.1      Bull Market
38                7         0        2             1      1  2026            323               17.7                   2                   8.4                 10.0        7970             0                    77.4                5                  18.3                    10.3                  -1.6                8.3                 4.1                 5.3           Stable
39                5         5        3             3      9  2024          10860               39.9                   1                  10.1                 10.0        1531             1                    40.2                0                 -17.3                    -3.6                 -13.8                8.3                 2.5                 2.7        Recession
40               17         0        5             2     10  2024           2181                7.1                   2                   5.7                 10.0        1770             3                    51.6                2                  29.5                    22.7                  18.4                7.8                 6.7                 5.2           Stable
41               19         6        3             1      8  2024          12470               33.1                   0                   1.7                  9.9        1777             1                    11.2                3                  34.6                     8.3                  -7.2                1.3                 6.2                 2.7        Recession
42               13         5        4             3      7  2026           1358                4.0                   2                   7.2                 10.0         337             2                    84.1                1                 -10.1                    14.0                  16.8                5.6                 7.1                 5.7      Bull Market
43               11         6        1             0      3  2024          13015               18.9                   1                   8.0                 10.0        1447             2                    65.8                7                  49.0                    10.0                   9.2                6.7                 5.8                 5.4        Recession
44               14         0        4             2      4  2025           3222                1.7                   2                   5.0                  4.0        7981             0                    19.7                5                 -17.1                     6.0                   5.2                6.4                 7.8                 6.3           Stable
45                8         4        2             2      6  2026           6240               30.0                   4                   9.5                 10.0         386             2                    32.2                2                  56.0                    -9.3                 -14.4                8.2                 3.8                 2.7        Recession
46                5         6        2             2      5  2024           2125                4.6                   1                   9.4                  3.5        5326             0                    65.0                5                  56.2                   -22.4                   0.3                6.6                 5.4                 6.0      Bull Market
47               16         5        1             2      2  2024           5850                7.4                   4                   1.2                  1.9         325             2                    19.6                5                  35.1                    32.7                  17.6                1.9                 7.4                 7.0           Stable
48                8         5        1             2      6  2025           2081                5.6                   1                   7.2                  6.8        2860             3                    39.0                3                  32.1                     5.3                  13.1                5.8                 7.1                 5.7      Bull Market
49                1         0        3             2      8  2024           1833                7.2                   2                   2.2                  2.4        4735             2                    81.7                2                  25.8                     9.9                  12.4                1.9                 5.2                 6.9           Stable
50                7         6        0             0      4  2024           9837               39.2                   2                  11.1                 10.0         243             1                    54.5                1                  -7.2                    40.4                   3.0                9.7                 4.4                 3.1        Recession
51               11         2        4             3      6  2026            112                5.3                   2                   7.7                  6.5        2117             3                    22.3                4                  26.9                   -20.6                 -10.3                5.6                 4.5                 4.7      Bull Market

In [17]:
df.columns

Index(['company_name', 'industry', 'country', 'company_size', 'month', 'year',
       'layoffs_count', 'layoff_percentage', 'reason_for_layoffs',
       'ai_automation_impact', 'ai_replacement_risk', 'open_roles',
       'hiring_trend', 'remote_jobs_percentage', 'top_hiring_role',
       'stock_growth_percent', 'revenue_growth_percent',
       'salary_budget_change', 'ai_adoption_level', 'employee_sentiment',
       'job_security_score', 'market_condition'],
      dtype='str')

In [18]:
x=df[['company_name', 'industry', 'country', 'company_size', 'month', 'year',
       'layoffs_count', 'layoff_percentage', 'reason_for_layoffs',
       'ai_automation_impact', 'ai_replacement_risk', 'open_roles',
       'hiring_trend', 'remote_jobs_percentage', 'top_hiring_role',
       'stock_growth_percent', 'revenue_growth_percent',
       'salary_budget_change', 'ai_adoption_level', 'employee_sentiment',
       'job_security_score']]

y=df['market_condition']

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
model=RandomForestClassifier(
    n_estimators=50 #it shows how many decision trees you have to plot
)
model.fit(x_train,y_train)

RandomForestClassifier(n_estimators=50)

In [25]:
predict=model.predict(x_test)

predict

array(['Bull Market', 'Bull Market', 'Bull Market', ..., 'Stable',
       'Stable', 'Recession'], shape=(2400,), dtype=object)

In [26]:
score=classification_report(y_test,predict)
print(score)

              precision    recall  f1-score   support

 Bull Market       0.82      1.00      0.90       755
   Recession       0.98      0.91      0.95       829
      Stable       0.90      0.78      0.84       816

    accuracy                           0.89      2400
   macro avg       0.90      0.90      0.89      2400
weighted avg       0.90      0.89      0.89      2400

In [27]:
import pickle

pickle.dump(model,open('random.pkl','wb'))
print("Pickle file created successfully..")

Pickle file created successfully..